### PR TITLE
Set up the initial backend environment

### PR DESCRIPTION
**Pull request by DrakeHunterK7**
Set up the whole backend environment so others can pull from it and get the environment set up on their own local PC.

### CODE REVIEW

**Comment by ChenChenYellow** [comment]
Please review if database was setup correctly.

**Comment by ChenChenYellow** [comment]
Capture_4

**Comment by AutoSleep** [comment]
the database and backend env setup is finished 
follow up: @ChenChenYellow  please share your google cloud permission to all the teammates,
otherwise, we can access the database

**Comment by ChenChenYellow** [comment]
The credentials are
The email is SOEN341T300@gmail.com
The password is Soen_341_T_300

**Comment by AutoSleep** [comment]
thank you so much for your effort

**Comment by DrakeHunterK7** [comment]
Can confirm the environment setup, thanks @ChenChenYellow

**Pull request merged**
